import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { GetStaticProps } from 'next';

interface Nationality {
  name: string;
  country: Country[];
}

interface Country {
  country_id: string;
  probability: number;
}

const Home: NextPage<Nationality> = (nationality: Nationality) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SSR test - {nationality.name}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>This is a SSR TEST</h1>

        <p className={styles.description}>Let's see if it works - {nationality.name}</p>

        {nationality && (
          <div className={styles.grid}>
            {nationality.country.map((country, i) => {
              return (
                <article key={`country-${country.country_id}-${i}`} className={styles.card}>
                  <h2>{country.country_id}</h2>
                  <p>{country.probability}</p>
                </article>
              );
            })}
          </div>
        )}
      </main>

      <footer className={styles.footer}>Powered by Jurgen</footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch('https://api.nationalize.io/?name=nicolai');
  const nationality = await res.json();
  return {
    props: nationality,
  };
};

export default Home;
