import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

interface PageContent {
  nationality: Nationality;
  bacon: string[];
}

interface Nationality {
  name: string;
  country: Country[];
}

interface Country {
  country_id: string;
  probability: number;
}

const Home: NextPage<PageContent> = ({ nationality, bacon }: PageContent) => {
  console.log(bacon);
  return (
    <div className={styles.container}>
      <Head>
        <title>SSR test - {nationality.name}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>This is a SSR TEST</h1>

        <p className={styles.description}>Let&apos;s see if it works - {nationality.name}</p>

        {nationality && (
          <div className={styles.grid}>
            {nationality.country.map((country, i) => {
              return (
                <article key={`country-${country.country_id}-${i}`} className={styles.card}>
                  <h2>{country.country_id}</h2>
                  <p>{country.probability}</p>
                </article>
              );
            })}
          </div>
        )}

        <p className={styles.description}>Bacon</p>
        {nationality && (
          <div className={styles.grid}>
            {bacon.map((bacon, i) => {
              return (
                <article key={`bacon-${i}`} className={styles.card}>
                  <p>{bacon}</p>
                </article>
              );
            })}
          </div>
        )}
      </main>

      <footer className={styles.footer}>Powered by Jurgen</footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const nationalityRes = await fetch('https://api.nationalize.io/?name=nicolai');
  const nationality = await nationalityRes.json();
  const baconRes = await fetch('https://baconipsum.com/api/?type=meat-and-filler');
  const bacon = await baconRes.json();
  return {
    props: {
      nationality,
      bacon,
    },
    revalidate: 20, // In seconds
  };
};

export default Home;
